language: node_js
sudo: false
node_js:
- '6'
branches:
  only:
  - master
  - develop
  - fix-travisyml
  - "/v\\d+\\.\\d+\\.\\d+?.*/"
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=cam51p.g@gmail.com
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=cam51p.g@gmail.com
cache:
  directories:
  - node_modules
install:
  - npm install
before_script:
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'cam51p.g@gmail.com'
  - rm -rf public
  - git clone --depth=1 --branch=gh-pages https://github.com/asakusarb/oedo07.github.io.git public
  - pushd public
  - git ls-files | xargs -I {} rm -rf {}
  - popd
script:
  - npm run gulp build
  - ls -la public
  - cd public
  - git add -A
  - git commit -m 'Update'
  - 'git push --force https://$GH_TOKEN@github.com/asakusarb/oedo07.github.io.git HEAD:gh-pages'
